#
#       AUTHOR - Raman Sailopal
#
#       docker compose yml file for the YottaDB/Rust/Theia IDE stack
#
version: "2"
services:
 yottarust:
   image: docker.io/ramb0/yotta-rust:latest
   networks:
      - yottanet
   mem_limit: 1G
   volumes:
      - "$yottadatadir:/data"
      - "$rustcode:/usr/local/YDBRust"
      - app-volume:/home/project
      - ../.ssh:/root/.ssh
      - ../lsyncd/lsyncd.conf:/etc/lsyncd.conf
 ide:
   image: docker.io/ramb0/theia-mumps:latest
   ports:
      - 3002:3000
      - 9229:9229
   networks:
      - yottanet
   volumes:
      - app-volume:/home/project
      - ../project:/home/yottadb-settings
      - ../.ssh:/root/.ssh
      - .theia:/home/theia/.theia
 yottaglbview:
   image: docker.io/ramb0/yotta-glbview:latest
   ports:
      - 8001:8001
   environment:
     - glbviewport=8001
     - glbviewadd=$glbviewadd
     - yotta_dir=/data
     - ydb_dir=/data
     - ydb_rel=$yottavers
     - ydb_gbl="/data/$yottavers/g/yottadb"
   networks:
      - yottanet
   volumes:
      - "$yottadatadir:/data"


networks:
    yottanet:
volumes:
    app-volume:

