FROM docker.io/yottadb/yottadb-base 
COPY rcomp.sh /usr/local/bin/rcomp.sh
COPY start.sh /usr/local/bin/start.sh
COPY rcopy.sh /usr/local/bin/rcopy.sh
RUN apt-get update
RUN apt-get install -y openssh-server 
RUN apt-get install -y clang 
RUN apt-get install -y cargo
RUN apt-get install -y git
RUN apt-get install -y lsyncd
RUN cp /opt/yottadb/current/libyottadb.so /usr/lib
RUN /opt/yottadb/current/ydb
WORKDIR /usr/local
RUN git clone https://gitlab.com/YottaDB/Lang/YDBRust.git
ENTRYPOINT service ssh start && /usr/local/bin/start.sh
